// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: mandelbrot.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageContent []byte `protobuf:"bytes,1,opt,name=imageContent,proto3" json:"imageContent,omitempty"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mandelbrot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_mandelbrot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_mandelbrot_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetImageContent() []byte {
	if x != nil {
		return x.ImageContent
	}
	return nil
}

var File_mandelbrot_proto protoreflect.FileDescriptor

var file_mandelbrot_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x6c, 0x62, 0x72, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x2b, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x32, 0x38, 0x0a, 0x0a,
	0x4d, 0x61, 0x6e, 0x64, 0x65, 0x6c, 0x62, 0x72, 0x6f, 0x74, 0x12, 0x2a, 0x0a, 0x08, 0x47, 0x65,
	0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x06,
	0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x6f, 0x69, 0x69, 0x64, 0x6f, 0x72, 0x2f, 0x67, 0x6f, 0x2d,
	0x67, 0x72, 0x70, 0x63, 0x2d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x6c, 0x62, 0x72, 0x6f, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mandelbrot_proto_rawDescOnce sync.Once
	file_mandelbrot_proto_rawDescData = file_mandelbrot_proto_rawDesc
)

func file_mandelbrot_proto_rawDescGZIP() []byte {
	file_mandelbrot_proto_rawDescOnce.Do(func() {
		file_mandelbrot_proto_rawDescData = protoimpl.X.CompressGZIP(file_mandelbrot_proto_rawDescData)
	})
	return file_mandelbrot_proto_rawDescData
}

var file_mandelbrot_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mandelbrot_proto_goTypes = []interface{}{
	(*Image)(nil),         // 0: Image
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_mandelbrot_proto_depIdxs = []int32{
	1, // 0: Mandelbrot.GetImage:input_type -> google.protobuf.Empty
	0, // 1: Mandelbrot.GetImage:output_type -> Image
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mandelbrot_proto_init() }
func file_mandelbrot_proto_init() {
	if File_mandelbrot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mandelbrot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mandelbrot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mandelbrot_proto_goTypes,
		DependencyIndexes: file_mandelbrot_proto_depIdxs,
		MessageInfos:      file_mandelbrot_proto_msgTypes,
	}.Build()
	File_mandelbrot_proto = out.File
	file_mandelbrot_proto_rawDesc = nil
	file_mandelbrot_proto_goTypes = nil
	file_mandelbrot_proto_depIdxs = nil
}
